SET IDENTITY_INSERT [dbo].[PostAdClient] ON
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 0, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 1, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 2, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 3, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 4, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 5, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 6, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 7, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 8, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 9, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 10, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'pump not working', 11, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Security, Fire & Safety', N'Alarm set off', N'alarm is not behaving', 12, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Security, Fire & Safety', N'Alarm set off', N'alarm is not behaving', 13, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Garden and Landscaping', N'dirty garden', N'flower dead', 15, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Garden and Landscaping', N'dirty garden', N'flower are dying', 16, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Garden and Landscaping', N'dirty garden', N'nh', 17, NULL)
INSERT INTO [dbo].[PostAdClient] ([Category], [AdTitle], [AdDescription], [PostAdId], [UserName]) VALUES (N'Pool Specialist', N'Dirty Pool', N'bg', 18, NULL)
SET IDENTITY_INSERT [dbo].[PostAdClient] On
